# Generated by Django 2.0.5 on 2018-05-28 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_physicaluser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementStateRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_registration', models.CharField(choices=[('vun', 'Виникнення'), ('prup', 'Припинення'), ('per', 'Перехід')], max_length=200, verbose_name='Вид реєстрації')),
                ('property_list_number', models.IntegerField(verbose_name='Номер запису про право власності')),
                ('ownership', models.CharField(choices=[('private', 'Приватна'), ('state', 'Державна'), ('other_state', 'власність інших '), ('comunal', 'Комунальна'), ('owner_international', 'Власність міжнародних організацій і юридичних осіб інших держав')], max_length=100, verbose_name='Форма власності')),
                ('common_property_type', models.CharField(choices=[('juically_compatible', 'Спільна сумісна'), ('join_partially', 'Спільна часткова')], max_length=100, verbose_name='Форма власності')),
                ('object_type', models.CharField(choices=[('land_plot', 'Земельна ділянка'), ('non_residential_premises', 'Не житлове приміщення'), ('living_room', 'житлове приміщення'), ('flat', 'Квартира')], max_length=100, verbose_name='Тип обьекта')),
                ('register_number', models.IntegerField(verbose_name='Реєстраційний номер')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Address', verbose_name='Адрес')),
            ],
        ),
    ]
