# Generated by Django 2.0.5 on 2018-05-29 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForCancelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cancelation', models.CharField(choices=[('record', 'Cкасування запису Державного реєстру речових прав на нерухоме майно'), ('registration', 'Cкасування державної реєстрації речових прав на нерухоме майно та їх обтяжень')], max_length=50, verbose_name='Вид скасування')),
                ('application_registration_number', models.IntegerField(verbose_name='Реєстраційний номер об’єкта нерухомого майна')),
                ('property_record_number', models.IntegerField(blank=True, null=True, verbose_name='Номер запису про право власності')),
                ('record_number_other_properties_right', models.IntegerField(blank=True, null=True, verbose_name='Номер запису про інше речове право')),
                ('encumbrance_record_number', models.IntegerField(blank=True, null=True, verbose_name='Номер запису про обтяження')),
                ('motgage_record_number', models.IntegerField(blank=True, null=True, verbose_name='Номер запису про іпотеку')),
                ('record_number_nonowner_real_estate', models.IntegerField(blank=True, null=True, verbose_name='Номер запису про взяття на облік  безхазяйного нерухомого майна')),
                ('grounds_for_cancelation', models.CharField(max_length=255, verbose_name='Підстава для скасування')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('on_view', 'розгляд'), ('failure', 'відмова'), ('approved', 'схвалено'), ('dont_read', 'не прочитаний')], default='dont_read', max_length=255, verbose_name='Статус')),
                ('registor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Registor', verbose_name='Реєстратор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.PhysicalUser', verbose_name='Юзер')),
            ],
        ),
        migrations.CreateModel(
            name='StatementStateRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_registration', models.CharField(choices=[('vun', 'Виникнення'), ('prup', 'Припинення'), ('per', 'Перехід')], max_length=200, verbose_name='Вид реєстрації')),
                ('property_list_number', models.IntegerField(verbose_name='Номер запису про право власності')),
                ('ownership', models.CharField(choices=[('private', 'Приватна'), ('state', 'Державна'), ('other_state', 'власність інших '), ('comunal', 'Комунальна'), ('owner_international', 'Власність міжнародних організацій і юридичних осіб інших держав')], max_length=100, verbose_name='Форма власності')),
                ('common_property_type', models.CharField(blank=True, choices=[('juically_compatible', 'Спільна сумісна'), ('join_partially', 'Спільна часткова')], max_length=100, null=True, verbose_name='Вид спільної власності')),
                ('object_type', models.CharField(choices=[('land_plot', 'Земельна ділянка'), ('non_residential_premises', 'Не житлове приміщення'), ('living_room', 'житлове приміщення'), ('flat', 'Квартира')], max_length=100, verbose_name='Тип обьекта')),
                ('register_number', models.IntegerField(verbose_name='Реєстраційний номер')),
                ('status', models.CharField(choices=[('on_view', 'розгляд'), ('failure', 'відмова'), ('approved', 'схвалено'), ('dont_read', 'не прочитаний')], default='dont_read', max_length=255, verbose_name='Статус')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Address', verbose_name='Адреса')),
                ('registor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Registor', verbose_name='Реєстратор')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.PhysicalUser')),
            ],
        ),
    ]
