# Generated by Django 2.0.5 on 2018-05-28 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_physicaluser_phone_number'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementstateregistration',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.PhysicalUser'),
        ),
    ]
