# Generated by Django 2.0.5 on 2018-05-30 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationforcancelation',
            name='registor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='registrator.Registor', verbose_name='Реєстратор'),
        ),
        migrations.AlterField(
            model_name='statementstateregistration',
            name='registor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='registrator.Registor', verbose_name='Реєстратор'),
        ),
    ]
