# Generated by Django 2.0.5 on 2018-05-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_physicaluser_phone_number'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForCancelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cancelation', models.CharField(choices=[('record', 'Cкасування запису Державного реєстру речових прав на нерухоме майно'), ('registration', 'Cкасування державної реєстрації речових прав на нерухоме майно та їх обтяжень')], max_length=50, verbose_name='Вид скасування')),
                ('application_registration_number', models.IntegerField(verbose_name='Реєстраційний номер об’єкта нерухомого майна')),
                ('property_record_number', models.IntegerField(verbose_name='Номер запису про право власності')),
                ('record_number_other_properties_right', models.IntegerField(verbose_name='Номер запису про інше речове право')),
                ('encumbrance_record_number', models.IntegerField(verbose_name='Номер запису про обтяження')),
                ('motgage_record_number', models.IntegerField(verbose_name='Номер запису про іпотеку')),
                ('record_number_nonowner_real_estate', models.IntegerField(verbose_name='Номер запису про взяття на облік  безхазяйного нерухомого майна')),
                ('grounds_for_cancelation', models.CharField(max_length=255, verbose_name='Підстава для скасування')),
                ('date', models.DateField(verbose_name='Дата')),
                ('registor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Registor', verbose_name='Реєстратор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.PhysicalUser', verbose_name='Юзер')),
            ],
        ),
    ]
