# Generated by Django 2.0.5 on 2018-05-28 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_applicationforcancelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationforcancelation',
            name='registor',
        ),
    ]
