# Generated by Django 2.0.5 on 2018-05-29 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_statementstateregistration_user'),
        ('documents', '0003_remove_applicationforcancelation_registor'),
    ]

    operations = [
    ]
