# Generated by Django 2.0.5 on 2018-05-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_merge_20180529_0801'),
        ('documents', '0004_merge_20180529_0303'),
        ('documents', '0004_merge_20180529_0302'),
    ]

    operations = [
    ]
