# Generated by Django 2.0.5 on 2018-05-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_merge_20180529_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationforcancelation',
            name='encumbrance_record_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер запису про обтяження'),
        ),
        migrations.AlterField(
            model_name='applicationforcancelation',
            name='motgage_record_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер запису про іпотеку'),
        ),
        migrations.AlterField(
            model_name='applicationforcancelation',
            name='property_record_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер запису про право власності'),
        ),
        migrations.AlterField(
            model_name='applicationforcancelation',
            name='record_number_nonowner_real_estate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер запису про взяття на облік  безхазяйного нерухомого майна'),
        ),
        migrations.AlterField(
            model_name='applicationforcancelation',
            name='record_number_other_properties_right',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер запису про інше речове право'),
        ),
    ]
