<<<<<<< HEAD
# Generated by Django 2.0.5 on 2018-05-29 23:22
=======
# Generated by Django 2.0.5 on 2018-05-30 09:32
>>>>>>> 502afffe72bb357fe54097a9caeba3094e6d653c

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Країна')),
                ('region', models.CharField(max_length=255, verbose_name='Регіон')),
                ('city', models.CharField(max_length=255, verbose_name='Місто')),
                ('street', models.CharField(max_length=255, verbose_name='Вулиця')),
                ('bilding_type', models.CharField(choices=[('build', 'Будинок'), ('ground_dil', 'Земельна ділянка')], max_length=255, verbose_name='Тип будівлі')),
                ('numberbild', models.IntegerField(verbose_name='Номер будинку')),
                ('kv', models.IntegerField(verbose_name='Номер квартири/земельної ділянки')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(max_length=255, verbose_name='document type')),
                ('status', models.CharField(max_length=255, verbose_name='status')),
                ('idRegistrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrator.Registor')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default=None, max_length=255, verbose_name='Логін')),
                ('password_legal', models.CharField(max_length=255, verbose_name='Пароль')),
                ('password_legal2', models.CharField(default=None, max_length=255, verbose_name='Потвердите пароль')),
                ('EDRPOU', models.IntegerField(default=None, verbose_name='EDRPOU')),
                ('name_company', models.CharField(max_length=255, verbose_name='name company')),
                ('first_name_LeadCompany', models.CharField(max_length=255, verbose_name='first_name')),
                ('last_name_LeadCompany', models.CharField(max_length=255, verbose_name='last_name')),
                ('middle_name_LeadCompany', models.CharField(max_length=255, verbose_name='middle_name')),
                ('tax_number_person', models.IntegerField(verbose_name='tax number')),
                ('adress_company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Address')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логін')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('password2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Потвердите пароль')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ім’я')),
                ('second_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('middle_name', models.CharField(max_length=255, verbose_name='По батькові')),
                ('phone_number', models.CharField(default='', max_length=255, verbose_name='Телефонний номер')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('passport_number', models.IntegerField(blank=True, null=True, verbose_name='Номер паспорта')),
                ('passport_serial', models.CharField(blank=True, max_length=2, null=True, verbose_name='Серія паспорта')),
                ('date_issue', models.DateField(blank=True, null=True, verbose_name='Коли виданий')),
                ('publisher', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ким виданий')),
                ('id_card', models.CharField(blank=True, max_length=255, null=True, verbose_name='id card')),
                ('ipn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ідентифікаціонний код')),
                ('adress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Address', verbose_name='Адрес')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='id_legal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.LegalPerson'),
        ),
        migrations.AddField(
            model_name='document',
            name='id_physical',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.PhysicalUser'),
        ),
    ]
