# Generated by Django 2.0.5 on 2018-05-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaluser',
            name='id_card',
            field=models.IntegerField(blank=True, null=True, verbose_name='id card'),
        ),
    ]
