# Generated by Django 2.0.5 on 2018-05-27 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180527_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaluser',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Address', verbose_name='Адрес'),
        ),
    ]
