# Generated by Django 2.0.5 on 2018-05-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180527_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaluser',
            name='password2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Потвердите пароль'),
        ),
    ]
