# Generated by Django 2.0.5 on 2018-05-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180527_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaluser',
            name='date_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Коли виданий'),
        ),
        migrations.AlterField(
            model_name='physicaluser',
            name='ipn',
            field=models.CharField(max_length=255, verbose_name='Ідентифікаціонний код'),
        ),
        migrations.AlterField(
            model_name='physicaluser',
            name='passport_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='physicaluser',
            name='passport_serial',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Серія паспорта'),
        ),
        migrations.AlterField(
            model_name='physicaluser',
            name='publisher',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ким виданий'),
        ),
    ]
