# Generated by Django 2.0.5 on 2018-05-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180527_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaluser',
            name='ipn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ідентифікаціонний код'),
        ),
    ]
