# Generated by Django 2.0.5 on 2018-05-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180527_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaluser',
            name='id_card',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id card'),
        ),
    ]
