# Generated by Django 2.0.5 on 2018-05-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180527_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicaluser',
            name='phone_number',
            field=models.CharField(default='', max_length=255, verbose_name='Телефонний номер'),
        ),
    ]
