# Generated by Django 2.0.5 on 2018-05-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_physicaluser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='bilding_type',
            field=models.CharField(choices=[('build', 'Будинок'), ('ground_dil', 'Земельна ділянка')], max_length=255, verbose_name='Тип будівлі'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='address',
            name='kv',
            field=models.IntegerField(verbose_name='Номер квартири'),
        ),
        migrations.AlterField(
            model_name='address',
            name='numberbild',
            field=models.IntegerField(verbose_name='Номер будинку'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(max_length=255, verbose_name='Регіон'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='EDRPOU',
            field=models.IntegerField(default=None, verbose_name='EDRPOU'),
        ),
    ]
