# Generated by Django 2.0.5 on 2018-05-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180529_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='kv',
            field=models.IntegerField(verbose_name='Номер квартири/земельної ділянки'),
        ),
    ]
